import { ipcRenderer, contextBridge } from 'electron';

contextBridge.exposeInMainWorld('aegisAPI', {
  processPrompt: (prompt: string) => ipcRenderer.invoke('aegis:processPrompt', prompt),
  fetchStewardLogs: (limit?: number) => ipcRenderer.invoke('aegis:fetchStewardLogs', limit),
  fetchCoreHealth: () => ipcRenderer.invoke('aegis:fetchCoreHealth'),
  fetchCoreSessions: () => ipcRenderer.invoke('aegis:fetchCoreSessions'),
  fetchCoreSessionSummary: (sessionId: string) => ipcRenderer.invoke('aegis:fetchCoreSessionSummary', sessionId),
  seedCoreSession: (sessionId?: string) => ipcRenderer.invoke('aegis:seedCoreSession', sessionId),
  runCoreScan: (sessionId: string, signal?: string) => ipcRenderer.invoke('aegis:runCoreScan', sessionId, signal),
  appendCorePeer: (sessionId: string, presentState: unknown) => ipcRenderer.invoke('aegis:appendCorePeer', sessionId, presentState),
  appendCorePCT: (sessionId: string, workingContext: unknown, retrievedRecordIds?: string[]) => ipcRenderer.invoke('aegis:appendCorePCT', sessionId, workingContext, retrievedRecordIds),
  writeCoreSpine: (sessionId: string, pattern: string, invariant?: boolean) => ipcRenderer.invoke('aegis:writeCoreSpine', sessionId, pattern, invariant),
  compressCoreNCT: (sessionId: string, distilledSummary: string, sourceRecordIds?: string[], pivots?: string[]) => ipcRenderer.invoke('aegis:compressCoreNCT', sessionId, distilledSummary, sourceRecordIds, pivots),
  requestCoreSSSP: (sessionId: string, trigger?: string) => ipcRenderer.invoke('aegis:requestCoreSSSP', sessionId, trigger),
  selectWorkspace: () => ipcRenderer.invoke('aegis:selectWorkspace'),
  readWorkspaceFile: (workspacePath: string, relativePath: string) => ipcRenderer.invoke('aegis:readWorkspaceFile', workspacePath, relativePath),
  saveAgent: (workspacePath: string, agentId: string, agentData: any) => ipcRenderer.invoke('aegis:saveAgent', workspacePath, agentId, agentData),
  loadAgent: (workspacePath: string, agentId: string) => ipcRenderer.invoke('aegis:loadAgent', workspacePath, agentId),
  writeWorkspaceFile: (workspacePath: string, relativePath: string, content: string) => ipcRenderer.invoke('aegis:writeWorkspaceFile', workspacePath, relativePath, content),
  executeTerminal: (workspacePath: string, command: string) => ipcRenderer.invoke('aegis:executeTerminal', workspacePath, command),
  getDaemonToken: () => ipcRenderer.invoke('aegis:getDaemonToken'),
  getMetrics: () => ipcRenderer.invoke('aegis:getMetrics'),
  triggerAlert: (message: string, severity: string) => ipcRenderer.invoke('aegis:triggerAlert', message, severity),
  configureWebhook: (url: string) => ipcRenderer.invoke('aegis:configureWebhook', url),
  getBackups: (workspacePath: string) => ipcRenderer.invoke('aegis:getBackups', workspacePath),
  restoreBackup: (workspacePath: string, backupFilename: string, relativeTarget: string) => ipcRenderer.invoke('aegis:restoreBackup', workspacePath, backupFilename, relativeTarget),
  fetchPrimeStatus: () => ipcRenderer.invoke('aegis:fetchPrimeStatus'),
  fetchPrimeImpact: () => ipcRenderer.invoke('aegis:fetchPrimeImpact'),
  fetchPrimeSignals: () => ipcRenderer.invoke('aegis:fetchPrimeSignals')
});
